### PR TITLE
yeet earlier `this.keymaps.loadBundledKeymaps` call

### PR DESCRIPTION
**Pull request by Meadowsys**
This is called once in the constructor, then again in `initialize`. The constructor call was too early, and `i18n.t` had not been available yet, but it was used indirectly by `loadBundledKeymaps`, causing stuff to crash.

PS. **_PAY ATTENTION TO CI TESTS_**

### CODE REVIEW

**Comment by Spiker985** [comment]
Looks like as of right now (with ~10 packages still testing)
- `find-and-replace` is within margins
- [Grammar Selector](https://github.com/pulsar-edit/pulsar/actions/runs/4623995051/jobs/8178554706) is failing
- [Settings-View](https://github.com/pulsar-edit/pulsar/actions/runs/4623995051/jobs/8178555849) is failing
- [Symbols-View](https://github.com/pulsar-edit/pulsar/actions/runs/4623995051/jobs/8178556445) has two more failures than normal
- `tree-view` is within margins

**Comment by confused-Techie** [comment]
@Spiker985 @Meadowsys 
I should mention that the `symbols-view` failures might be due to something else.

I've noticed the two additional failures over on #453 & #452

**Comment by confused-Techie** [comment]
Also just confirmed, looks like the earliest the failures of `symbols-view` appear (the 2 additional failures that is) is in #435 so second mate caused them, so don't hold them accountable here. But otherwise the others still apply of course

**Comment by Meadowsys** [comment]
slightly off topic, are the expected failures kept track of somewhere?

**Comment by Spiker985** [comment]
> slightly off topic, are the expected failures kept track of somewhere?

Tests channel in the discord is where confused has been pinning them

**Comment by Spiker985** [comment]
Looks like the editor tests are running _very_ long. It also looks like the MenuManager specs need updating

When the initial localization support was added, were the specs validated to make sure they were returning properly?

I also saw another `t is not a function` inside that spaghetti mess :thinking:

**Comment by confused-Techie** [comment]
@Spiker985 I've been trying to solve an issue that I thought was only on one of my PRs of the Editor tests running very very long.

I believe @Meadowsys mentioned they had seen it before and simply rerunning the tests was able to get it working.

Pretty sure my failed attempts to resolve this are in #424

**Comment by confused-Techie** [comment]
@Spiker985 yeah I'm seeing this in the editor tests

`"Uncaught (in promise) TypeError: Cannot read property 't' of undefined", source: /home/runner/work/pulsar/pulsar/src/menu-manager.js (244)`

But otherwise looks like the grammar tests, and extra failures elsewhere are now complaining about the `path` so improvement, we got new error messages

**Comment by Spiker985** [comment]
Looks like it's a renderer crash that causes the test to restart ad infinitum

You can see it on my PR for bumping the [editor test GHA](https://github.com/pulsar-edit/pulsar/actions/runs/4625521582/jobs/8181352985?pr=466#step:6:666)

**Comment by confused-Techie** [comment]
@Spiker985 Great find, looking further at the same test through our history

image

Doesn't look promising, especially in that [first failing](https://github.com/pulsar-edit/pulsar/actions/runs/4469710397/jobs/7852210474) test run pictured I'm seeing this `Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
Renderer process crashed, exiting`.

So it looks like maybe that PR has introduced some edge case causing a crash? But good to at least know what's causing the editor tests to be wonky, brings up a good point that we should probably also have a retry limit on these tests

**Comment by Meadowsys** [comment]
> `"Uncaught (in promise) TypeError: Cannot read property 't' of undefined", source: /home/runner/work/pulsar/pulsar/src/menu-manager.js (244)`

~~Looks like might be another "use before initialise" type of bug. [this line here in `menu-manager.js`](https://github.com/pulsar-edit/pulsar/blob/master/src/menu-manager.js#L71) is the culprit i think?~~ On second thought, that's just registering an event handler, so I'm not sure if this is the problem, but i'll post it anyways. Maybe the event fires too early, and i18n hasn't / is still being initialised or something? hm,

**Comment by Meadowsys** [comment]
I18n on master was reverted, going to remake the i18n PR and fix the bugs there (including this one) before it gets merged again
